name: 'Backport Action'
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: Token for the GitHub API.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: git-branch
  color: green
