name: 'Backport Action'
author: Søren Louv <sorenlouv@gmail.com>
description: 'Backport merged pull requests to other branches via labels'
inputs:
  github_token:
    description: Token for the GitHub API.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: git-branch
  color: green
